fix result file path issues
ossf/scorecard-action pull request #1428
Opened 2024-08-11 21:54 UTC by spencerschrock

There were two issues at play that prevented the binary from reading the correct results file:

1. The paths were not joined with a separator during the refactor in #1423. This led to file not found errors, as the file was saved in the wrong directory, with the wrong name.
2. The signing code tried to read the file from the working directory instead of the GitHub workspace directory.

I was able to test this code after modifying the testing command in the `Dockerfile` to use a different `GITHUB_WORKSPACE` directory. The signing portion of the code will need to wait until the e2e test to confirm the fix.

We should eventually improve the testing instructions, but at least the e2e test we have now caught this:
```shell
docker run -e GITHUB_REF=refs/heads/main \
     -e GITHUB_EVENT_NAME=branch_protection_rule \
    -e INPUT_RESULTS_FORMAT=json \
    -e INPUT_RESULTS_FILE=results.json \
    -e GITHUB_WORKSPACE="/home/runner/work/spencerschrock/actions-test" \
    -e INPUT_POLICY_FILE="/policy.yml" \
    -e INPUT_REPO_TOKEN=$GITHUB_AUTH_TOKEN \
    -e GITHUB_REPOSITORY="spencerschrock/actions-test" \
    -e GITHUB_EVENT_PATH="/event.json" \
    -e GITHUB_API_URL="https://api.github.com" \
    -e INPUT_PUBLISH_RESULTS="true" \
    -v /tmp/docker:/home/runner/work/spencerschrock/actions-test \
    spencerschrock/scorecard-action:latest
```

Fixes #1426
Fixes #1427

2024-08-11 22:25 UTC, justaugustus requested changes
Quick nit!

2024-08-11 22:25 UTC, justaugustus commented on internal/scorecard/format.go
> +	resultFile, err := os.Create(opts.GithubWorkspace + "/" + opts.InputResultsFile)
Maybe `filepath.Join` here instead?

2024-08-12 07:32 UTC, spencerschrock commented on internal/scorecard/format.go
> +	resultFile, err := os.Create(opts.GithubWorkspace + "/" + opts.InputResultsFile)
Done, thanks for the suggestion.

2024-08-12 10:00 UTC, justaugustus approved these changes
Thanks for the quick fix, @spencerschrock!

2024-08-12 10:00 UTC, merged