✨ Remove policy from action input
ossf/scorecard-action pull request #16
Opened 2021-12-06 17:51 UTC by laurentsimon

This PR removes the policy files as an input to the GitHub action. This will simplify the introduction of scorecard badges which we plan to build on top of raw results. Having scores for the action and raw results for the badges will make it difficult for users to map one to the other. In addition, most users keep the scores set to 10 for all checks in the policy files: it's easy to ignore. or set as "won't fix" in the GitHub scanning dashboard anyway.

2021-12-06 18:15 UTC, laurentsimon commented
cc @chrismcgehee

2021-12-07 16:55 UTC, azeemshaikh38 requested changes
Let's hold on this PR till we have an offline discussion.

2021-12-09 23:24 UTC, laurentsimon commented
friendly ping to LGTM as discussed offline

2021-12-11 01:31 UTC, azeemshaikh38 approved these changes

2021-12-11 01:31 UTC, merged