Default Branch Checking Bugfix
ossf/scorecard-action pull request #171
Opened 2022-04-11 18:06 UTC by rohankh532

PR to fix #169

2022-04-11 18:52 UTC, naveensrinivasan approved these changes
Looks good. @azeemshaikh38 👀

2022-04-21 17:04 UTC, naveensrinivasan commented
Shouldn't this target golang-staging branch?

2022-04-21 17:57 UTC, rohankh532 commented
> Shouldn't this target golang-staging branch?

Oops, fixed.

2022-04-21 18:15 UTC, azeemshaikh38 commented
> > Shouldn't this target golang-staging branch?
> 
> Oops, fixed.

This should not be `golang-staging`, merging this to `main` is the right thing to do. Copying my reply to Naveen over slack here: 

> we want to merge these changes to main  and after that to golang-staging . Basically, the only diff between main  and golang-staging  should be that the Dockerfile uses Golang instead of Bash. Everything else should be equivalent

2022-04-21 18:44 UTC, rohankh532 commented
> > > Shouldn't this target golang-staging branch?
> > 
> > 
> > Oops, fixed.
> 
> This should not be `golang-staging`, merging this to `main` is the right thing to do. Copying my reply to Naveen over slack here:
> 
> > we want to merge these changes to main  and after that to golang-staging . Basically, the only diff between main  and golang-staging  should be that the Dockerfile uses Golang instead of Bash. Everything else should be equivalent

Got it, changed back to main.

2022-04-21 19:58 UTC, azeemshaikh38 requested changes
LGTM overall. Revert the changes on Dockerfile and ensure that the unit tests are passing.

2022-04-21 19:58 UTC, azeemshaikh38 commented on Dockerfile
> +RUN CGO_ENABLED=0 make build
Dockerfile shouldn't be updated?

2022-04-21 20:21 UTC, rohankh532 commented on Dockerfile
> +RUN CGO_ENABLED=0 make build
Reverted this

2022-04-21 20:23 UTC, azeemshaikh38 approved these changes
Thanks!

2022-04-21 20:42 UTC, merged